# Generated by Django 4.2.14 on 2025-09-13 07:15

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('poi_type', models.CharField(choices=[('hospital', 'Hospital'), ('school', 'School'), ('metro', 'Metro Station')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sale_residential', 'For Sale: Houses & Apartments'), ('rent_residential', 'For Rent: Houses & Apartments'), ('land_plot', 'Lands & Plots'), ('rent_commercial', 'For Rent: Shops & Offices'), ('sale_commercial', 'For Sale: Shops & Offices'), ('pg_guest_house', 'PG & Guest Houses')], default='rent_residential', max_length=20)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('panorama_image', models.ImageField(blank=True, null=True, upload_to='panorama_images/')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Property Owner'), ('tenant', 'Tenant')], default='tenant', max_length=10)),
                ('shortlisted_properties', models.ManyToManyField(blank=True, to='core.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PGGuestHouseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_month', models.DecimalField(decimal_places=2, help_text='Price per bed, per month in Rupees', max_digits=10)),
                ('food_included', models.BooleanField(default=False, verbose_name='Is food included in the price?')),
                ('beds_per_room', models.PositiveIntegerField(default=1)),
                ('occupancy_type', models.CharField(choices=[('boys', 'Boys Only'), ('girls', 'Girls Only'), ('co-living', 'Co-Living (Unisex)')], default='co-living', max_length=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pg_guest_house_details', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandPlotDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_area', models.CharField(help_text='e.g., 2400 sqft or 1.5 acres', max_length=50)),
                ('is_gated_community', models.BooleanField(default=False, verbose_name='Is it a Gated Community?')),
                ('utilities_available', models.BooleanField(default=True, verbose_name='Are water and electricity available?')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price in Rupees', max_digits=12)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_plot_details', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForSaleResidentialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price in Rupees', max_digits=12)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_sale_residential_details', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='ForSaleCommercialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price in Rupees', max_digits=12)),
                ('square_feet', models.PositiveIntegerField()),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_sale_commercial_details', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='ForRentResidentialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('furnishing_status', models.CharField(choices=[('furnished', 'Furnished'), ('semi-furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_rent_residential_details', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='ForRentCommercialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_feet', models.PositiveIntegerField()),
                ('washrooms', models.PositiveIntegerField()),
                ('parking_available', models.BooleanField(default=True, verbose_name='Is parking available?')),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Rent per month in Rupees', max_digits=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_rent_commercial_details', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.property'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_tenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
