# Generated by Django 4.2.14 on 2025-09-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('sale_residential', 'For Sale: Houses & Apartments'), ('rent_residential', 'For Rent: Houses & Apartments'), ('land_plot', 'Lands & Plots'), ('rent_commercial', 'For Rent: Shops & Offices'), ('sale_commercial', 'For Sale: Shops & Offices'), ('pg_guest_house', 'PG & Guest Houses')], max_length=20),
        ),
    ]
