# Generated by Django 4.2.14 on 2025-09-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disliked_properties',
            field=models.ManyToManyField(blank=True, related_name='disliked_by', to='core.property'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_properties',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='core.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
