# Generated by Django 4.2.14 on 2025-09-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_role_vendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('sold', 'Sold')], default='available', max_length=10),
        ),
    ]
