# Generated by Django 4.2.14 on 2025-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_maintenancerequest_assigned_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Pending Approval', 'Work Complete (Pending Approval)'), ('Completed', 'Completed')], default='Submitted', max_length=20),
        ),
    ]
