# Generated by Django 4.2.14 on 2025-10-25 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_viewingappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='panorama_image',
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(help_text="e.g., 'Living Room', 'Kitchen'", max_length=100)),
                ('panorama_image', models.ImageField(upload_to='panorama_images/')),
                ('is_first_scene', models.BooleanField(default=False, help_text='Mark one scene as the starting point for the tour.')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.FloatField(help_text='Vertical position (up/down). Click on the panorama to find this.')),
                ('yaw', models.FloatField(help_text='Horizontal position (left/right). Click on the panorama to find this.')),
                ('text', models.CharField(help_text="Text to display when hovering over the hotspot (e.g., 'Go to Kitchen')", max_length=100)),
                ('source_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='core.scene')),
                ('target_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to_scene', to='core.scene')),
            ],
        ),
    ]
